### ISSUE TITLE
[Bug]: The GA worflows that use CI images are failing

### ISSUE THREAD

**Issue by reta** [opensearch-project/opensearch-ci#436]
### Describe the bug

I see that many GA workflows that use our own CI images are failing with:

```
 /usr/bin/docker exec  efbe92a44c7a1df6b6a8a07f701696d0a8552061642e21ea6ddfa25bb30be177 sh -c "cat /etc/*release | grep ^ID"
/__e/node20/bin/node: /lib64/libm.so.6: version `GLIBC_2.27' not found (required by /__e/node20/bin/node)
/__e/node20/bin/node: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /__e/node20/bin/node)
```

### To reproduce

- https://github.com/opensearch-project/custom-codecs/actions/runs/9848478425/job/27191143431?pr=162
- https://github.com/opensearch-project/ml-commons/actions/runs/9848491931/job/27190511458

### Expected behavior

There were no changes in any workflows

### Host / Environment

GA

**Comment by reta** [comment]
@peterzhuamazon fyi

**Comment by peterzhuamazon** [comment]
Hi @reta ,

This is due to Github enforcing node20 in github actions since 06/30/2024.
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/


For us, all OpenSearch related plugins (not dashboards) are still pulling AL2 images until 2025/06/30 before deprecation.
And AL2 does not support node20 due to glibc version is lower than 2.28.

You can use examples from this PR to fix this issue temporarily for now.
Note that you can only use action versions that was built on top of older nodejs version (ex: checkout@v3 instead of v4).
https://github.com/opensearch-project/k-NN/pull/1795

Thanks.

**Comment by peterzhuamazon** [comment]
We are closing this issue for now as it is not related to ci repo but rather github enforcing a dep verion 😄 .

See attached PRs for fix for your repo.

Thanks.
